"""Static contract for Elasticsearch helper functions."""

from typing import Any as Dynamic

def parallel_bulk(*args: Dynamic, **kwargs: Dynamic) -> Dynamic: ...
def streaming_bulk(*args: Dynamic, **kwargs: Dynamic) -> Dynamic: ...
def reindex(*args: Dynamic, **kwargs: Dynamic) -> Dynamic: ...
def scan(*args: Dynamic, **kwargs: Dynamic) -> Dynamic: ...
