"""Static contract for the optional gqlalchemy Memgraph client."""

from typing import Any as Dynamic

class Memgraph:
    def __init__(self, *args: Dynamic, **kwargs: Dynamic) -> None: ...
    def __getattr__(self, name: str) -> Dynamic: ...

class Node:
    def __init__(self, *args: Dynamic, **kwargs: Dynamic) -> None: ...
    def __getattr__(self, name: str) -> Dynamic: ...

class Relationship:
    def __init__(self, *args: Dynamic, **kwargs: Dynamic) -> None: ...
    def __getattr__(self, name: str) -> Dynamic: ...

class Path:
    def __init__(self, *args: Dynamic, **kwargs: Dynamic) -> None: ...
    def __getattr__(self, name: str) -> Dynamic: ...
