"""Static contract for PyTorch Geometric data containers."""

from typing import Any as Dynamic

class Data:
    def __init__(self, *args: Dynamic, **kwargs: Dynamic) -> None: ...
    def __getitem__(self, key: Dynamic) -> Dynamic: ...
    def __setitem__(self, key: Dynamic, value: Dynamic) -> None: ...
    def __getattr__(self, name: str) -> Dynamic: ...

class HeteroData(Data): ...
