"""Static contract for the optional GEKKO solver dependency."""

from typing import Any as Dynamic

class _Variable:
    value: list[float]
    def __add__(self, other: Dynamic) -> Dynamic: ...
    def __radd__(self, other: Dynamic) -> Dynamic: ...
    def __mul__(self, other: Dynamic) -> Dynamic: ...
    def __rmul__(self, other: Dynamic) -> Dynamic: ...
    def __ge__(self, other: Dynamic) -> Dynamic: ...

class _Options:
    SOLVER: int

class GEKKO:
    options: _Options
    def __init__(self, *args: Dynamic, **kwargs: Dynamic) -> None: ...
    def Const(self, *args: Dynamic, **kwargs: Dynamic) -> _Variable: ...
    def Var(self, *args: Dynamic, **kwargs: Dynamic) -> _Variable: ...
    def Equation(self, *args: Dynamic, **kwargs: Dynamic) -> Dynamic: ...
    def Intermediate(self, *args: Dynamic, **kwargs: Dynamic) -> Dynamic: ...
    def Obj(self, *args: Dynamic, **kwargs: Dynamic) -> Dynamic: ...
    def solve(self, *args: Dynamic, **kwargs: Dynamic) -> Dynamic: ...
