"""Static contract for optional torchmetrics runtime support."""

from typing import Any as Dynamic

class AUC:
    def __init__(self, *args: Dynamic, **kwargs: Dynamic) -> None: ...
    def __call__(self, *args: Dynamic, **kwargs: Dynamic) -> Dynamic: ...
    def __getattr__(self, name: str) -> Dynamic: ...

class Accuracy(AUC): ...
class F1Score(AUC): ...
class Precision(AUC): ...
class Recall(AUC): ...
